### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by FVFaleiro** [omargiorgetti/rpivotTabletocsv#1]
How can I install it in R? I have tried as below without success. 
Thanks!

`devtools::install_github("omargiorgetti/rpivotTabletocsv", ref="master")`

Error: HTTP error 404.
  Not Found

  Did you spell the repo owner (`omargiorgetti`) and repo name (`rpivotTabletocsv`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by omargiorgetti** [comment]
Good morning,
It's not a package it's a simple examples. You can download function.R and run the app.R script.
Omar
